- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
  become: "{{need_sudo}}"
- name: Install Poetry
  include_role:
      name: poetry
- name: Install Jupyter
  include_role:
        name: jupyter
- name: Install Docker
  include_role:
        name: docker
- name: Install Script_languages
  include_role:
      name: script_languages
- name: Clear pip cache
  ansible.builtin.file:
    path: /root/.cache/pip
    state: absent
