---

# - name: Install contrib nbextension
#   ansible.builtin.command: >
#     "{{jupyterlab.virtualenv}}/bin/jupyter" contrib nbextension install --user
# 
# - name: Enable the ipywidgets extension
#   ansible.builtin.command: >
#     "{{jupyterlab.virtualenv}}/bin/jupyter" nbextension enable --py widgetsnbextension --sys-prefix

# because the generate-config command below never overwrites an existing file
- name: Delete existing JupyterLab config file
  ansible.builtin.file:
    path: "{{ jupyterlab.config }}"
    state: absent

# this generates /root/.jupyter/jupyter_lab_config.py (it has all rows commented out)
# this config file is very large (>30K)
- name: Generate JupyterLab config
  ansible.builtin.command: "{{jupyterlab.virtualenv}}/bin/jupyter lab --generate-config"
  # this command automatically outputs to ~/.jupyter/

- name: Edit JupyterLab config with our settings
  ansible.builtin.lineinfile:
    path: "{{ jupyterlab.config }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - regexp: "c.NotebookApp.ip"
      line: "c.NotebookApp.ip = '{{ jupyterlab.ip }}'"
    - regexp: "c.NotebookApp.open_browser"
      line: "c.NotebookApp.open_browser = False"

- name: Generate a new password
  expect:
    command: "{{jupyterlab.virtualenv}}/bin/jupyter server password"
    responses:
      Enter password: "{{jupyterlab.password}}"
      Verify password: "{{jupyterlab.password}}"

- name: Create the notebook directory
  ansible.builtin.file:
    path: "{{jupyterlab.notebook_folder}}"
    state: directory
    mode: '0755'